### ISSUE TITLE
No custom lookup function allowed

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#162]
We have a customer who has a self written puppet lookup function: `puppet_function_lookup_key`
HDM does show error 500 when we select a node.

I already found `app/models/hiera_data/hierarchy.rb` has a mapping of functions and return yaml, json or eyaml. In this case we should use eyaml.

Is this possible to achieve?

**Comment by oneiros** [comment]
I am not sure how and if hdm can solve this. From what I gather, I custom lookup functions means that someone is using a fully custom backend, which (from hdm's point of view) could be anything.

And of course hardcoding this one instance to mean eyaml makes no sense, as it might mean something completely different for another user (especially since the name is very generic).

The only thing I can imagine right now, is that we add a configuration option in `config/hdm.yaml` where one can map custom lookup functions to existing backends. Something like:

```yaml
custom_lookup_function_mapping:
   puppet_function_lookup_key: eyaml
```

**Comment by tuxmea** [comment]
Please implement using the solution you described.
