### ISSUE TITLE
HDM should be able to read global hiera data

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#330]
### Discussed in https://github.com/betadots/hdm/discussions/299

<div type='discussions-op-text'>

<sup>Originally posted by **tuxmea** February 15, 2024</sup>
In some environments, the global hiera data is used (`/etc/puppetlabs/puppet/hiera.yaml`)
HDM should be able to also show global data.

Workflow in HDM:

- select environment
- select node

1. Global data:

HDM now reads the global hiera.yaml file, replaces the facts and finds the yaml files for the node and collects all Hiera keys.
The global hiera.yaml file may be absent. It should only be taken into account if it has a hierarchy key.

2. Environment data:

HDM reads the environment hiera.yaml file, replaces the facts and finds the yaml files for the node and collects all Hiera keys.

3. Select a key

When selecting a Hiera key, HDM should show the global directory/file structure similar to environment data on top of the environment data.
Global data and environment data views are each have a border around to visualize that these are different data sources.

4. Show result

Show result must first parse global data and environment data afterwards.
lookup_options are dealt in the same way as single environment data.
</div>

**Comment by oneiros** [comment]
I am knee deep into implementing this. It took quite a while but I am finally getting somewhere.

Here is a sneak peek:

![image](https://github.com/betadots/hdm/assets/68106/9f487b9b-59c2-437a-9173-51744f1239f3)

I have a question about the location of the global layer's `hiera.yml` file, though:

According to the hiera docs the location of the global hiera.yaml is `$confdir/hiera.yaml` by default and can be overridden in `puppet.conf` (as, I suspect, can `$confdir`). So it is not always in a fixed location.

Since I assume we do not want to start parsing `puppet.conf`, how about we add a configuration option to `hdm.yml` to set the location? This would also be very helpful for testing purposes.

**Comment by tuxmea** [comment]
looks good. And yes: please make the location of the global hiera.yaml file configurable.

**Comment by tuxmea** [comment]
One minor request: Instead of `Layer: global` and `Layer: environment`:

please use `Scope: global` and `Scope: environment`.

Otherwise people might get confused with hiera hierarchy layers.

**Comment by oneiros** [comment]
> One minor request: Instead of Layer: global and Layer: environment:
>
> please use Scope: global and Scope: environment.

I would be happy to use better terminology. But just to make sure: Do you really think is correct? The documentation very consistently refers to the different levels as "layers". They are introduced here:

https://www.puppet.com/docs/puppet/8/hiera_intro.html#hiera_config_layers

And they are referred to several times, e.g. here: https://www.puppet.com/docs/puppet/8/hiera_automatic#puppet_lookup, always as "layers".

Also, when I use the search feature on the documentation page, the top results for "layers" all refer to the these levels of configuration while a search for "scope" returns only results not related to this concept at all :man_shrugging:

**Comment by tuxmea** [comment]
Layout issue with short list of data:
<img width="1675" alt="image" src="https://github.com/betadots/hdm/assets/763214/39ff6e47-465a-4424-a614-644d6c177107">
