### ISSUE TITLE
Caching files

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#332]
### Discussed in https://github.com/betadots/hdm/discussions/281

<div type='discussions-op-text'>

<sup>Originally posted by **oneiros** January 26, 2024</sup>
We have been talking about performance a couple of times. Until now, hdm seems to do fine even on (large-ish) production data, but we know that parsing all those files on every request is at the very least quite wasteful.

While browsing puppet's source code I stumbled upon a clever yet simple mechanism they use: They cache file contents and the `mtime` of the file. If the file is to be read again, the `mtime` is checked and if it has not changed, the cached file contents are returned.

We could go a step further and cache the parsed file contents. I had thought of something similar before, but was wary of the consequences: We run in a multi-threaded, possibly multi-process environment (puma). And caching large files, possibly multiplied with the number of threads/processes can take up a lot of memory. The usual solution in a web application is to use external storage like `memcached` or `redis` for caching. But this would make hdm deployments more complex, which I do not believe we want.

Discovering puppet's solution made me think about this some more. And I now think this might be viable, if we make it optional.

1. Making caching "opt-in" via an option in `hdm.yml`, people in (memory-)constrained environments can simply decide not to use it at all.
2. If we use Rails' built-in cache store, this already is configurable with different backends. So if a very large installation suddenly wanted to use `memcached` to store the cached files, it is simply a matter of adding another configuration option.

(FWIW, as far as I am aware, there is absolutely no urgency for this. It is just something that occured to me and I did not want it to get lost.)</div>

**Comment by oneiros** [comment]
Interesting. I liked the idea a lot and almost dove into implementing it head first. But I remembered the old advice to never do performance related changes without benchmarking first. So I cobbled together a benchmark script hitting random endpoints to see how response times and memory usage develop over time.

I then hacked together a quick implementation of this idea, storing parsed hashes from files in the `Rails.cache`.

Surprisingly, memory usage went down (very) slightly. But even more surprisingly, response times went up. I had not expected this _at all_. Looks like the overhead of using the rails cache is bigger than parsing a couple of yaml files.

Mind you, this is all with the existing test data, on which hdm has always performed really well. I will try to generate a couple of really big yaml files and try again to see if that makes any difference.

**Comment by oneiros** [comment]
Turns out, I failed to check which cache store was being used. I could have sworn the default would be the in memory one, but it is in fact the file based one. So I just swapped parsing one file type for another :man_facepalming:

**Comment by oneiros** [comment]
Well, configuring the in memory cache store makes no big difference here. Still memory usage is down a little while response times are slightly up (probably not significant).

**Comment by tuxmea** [comment]
Does it make a difference if we preload a memory cache (similar to memcached) upon HDM start?
HDM should show that it is preloading the cache and return to main web page afterwards.
In the first implementation I am fine to have a button for refreshing the cache.

**Comment by oneiros** [comment]
> Does it make a difference if we preload a memory cache (similar to memcached) upon HDM start?

Only if caching has a significant impact, which I begin to doubt.

I generated a couple of yaml files with 10,000 keys each and repeated my measurements. I could finally observe a small difference, but still not significant enough to signal this approach is viable.

And I guess it kind of makes sense:

1. Recent changes already mean we do a lot less yaml parsing to begin with.
2. Rails cache stores also use serialization of the stored data, so there is a slight overhead.
3. And finally it seems as if this overhead is not so different from parsing yaml files on disk. It should be said that I am using an SSD here, results might be different for spinning drives.

This all got me curious and I tried to dig a little deeper. Since I now had quite a few keys I could easily see where things become slow. Only two pages were affected for me: Key index and detail views. Both render the full list of keys in the left column. And indeed this takes up most of the time.

I profiled the code, and a lot of time is taken up by rails' link generation. I removed the path generation and replaced it with simple string substitution. This did bring the load time down significantly. But still it is too long imo. And it scales linearly with the number of keys. So the couple of hundred milliseconds this little "optimzation" saves, would quickly be eaten up by simply adding another large(ish) yaml file.

I will close this issue for now, as I am no longer convinced that caching file contents will actually help. I do think we need to do something about that key list, though. But that is a different matter, so I will open a new issue for that.
